"""Fusion & Output Engine — renders ImpactAssessment into various output formats."""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from src.common.types import EntityGraph, ImpactAssessment


def render_markdown(assessment: ImpactAssessment) -> str:
    """Render an ImpactAssessment as a structured Markdown report."""
    lines: list[str] = []

    lines.append(f"# Economic Warfare Impact Assessment")
    lines.append(f"")
    lines.append(f"**Date:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Scenario Type:** {assessment.scenario_type.value.replace('_', ' ').title()}")
    lines.append(f"**Query:** {assessment.query.raw_query}")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(assessment.executive_summary)
    lines.append("")

    # Target Entities
    if assessment.query.target_entities:
        lines.append("## Target Entities")
        lines.append("")
        for entity in assessment.query.target_entities:
            lines.append(f"- {entity}")
        lines.append("")

    # Findings
    if assessment.findings:
        lines.append("## Findings")
        lines.append("")
        for i, finding in enumerate(assessment.findings, 1):
            confidence = finding.get("confidence", "N/A")
            category = finding.get("category", "General")
            badge = _confidence_badge(confidence)
            lines.append(f"### {i}. {category} {badge}")
            lines.append("")
            lines.append(finding.get("finding", ""))
            if finding.get("data"):
                lines.append("")
                lines.append("**Supporting Data:**")
                lines.append(f"```json")
                lines.append(json.dumps(finding["data"], indent=2, default=str))
                lines.append("```")
            lines.append("")

    # Friendly Fire
    lines.append("## Friendly Fire Assessment")
    lines.append("")
    if assessment.friendly_fire:
        lines.append("| Entity | Exposure Type | Estimated Impact | Details |")
        lines.append("|--------|---------------|------------------|---------|")
        for ff in assessment.friendly_fire:
            lines.append(
                f"| {ff.get('entity', 'N/A')} "
                f"| {ff.get('exposure_type', 'N/A')} "
                f"| {ff.get('estimated_impact', 'N/A')} "
                f"| {ff.get('details', 'N/A')} |"
            )
    else:
        lines.append("No significant friendly-fire exposure identified.")
    lines.append("")

    # Confidence Summary
    if assessment.confidence_summary:
        lines.append("## Confidence Summary")
        lines.append("")
        lines.append("| Domain | Confidence |")
        lines.append("|--------|------------|")
        for domain, conf in assessment.confidence_summary.items():
            lines.append(f"| {domain.replace('_', ' ').title()} | {_confidence_badge(conf.value)} |")
        lines.append("")

    # Recommendations
    if assessment.recommendations:
        lines.append("## Recommendations")
        lines.append("")
        for i, rec in enumerate(assessment.recommendations, 1):
            lines.append(f"{i}. {rec}")
        lines.append("")

    # Sources
    if assessment.sources:
        lines.append("## Sources")
        lines.append("")
        for src in assessment.sources:
            url_part = f" — [{src.url}]({src.url})" if src.url else ""
            lines.append(f"- {src.name}{url_part}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Economic Warfare OSINT System*")

    return "\n".join(lines)


def render_json(assessment: ImpactAssessment) -> str:
    """Render as structured JSON for downstream ingestion."""
    return assessment.model_dump_json(indent=2)


def render_entity_graph(entity_graph: EntityGraph) -> dict[str, Any]:
    """Render an EntityGraph directly to vis.js node/edge format."""
    colors = {
        "company": "#4A90D9", "person": "#7B68EE", "government": "#DC143C",
        "vessel": "#2E8B57", "sanctions_list": "#F85149",
        "theme": "#F0883E", "sector": "#3FB950",
    }
    nodes = [
        {
            "id": e.id,
            "label": e.name if len(e.name) <= 28 else e.name[:26] + "…",
            "group": e.entity_type,
            "title": e.name,
            "color": colors.get(e.entity_type, "#808080"),
        }
        for e in entity_graph.entities
    ]
    edges = [
        {
            "from": r.source_id, "to": r.target_id,
            "label": r.relationship_type.replace("_", " "),
            "arrows": "to", "dashes": r.confidence.value == "LOW",
        }
        for r in entity_graph.relationships
    ]
    return {"nodes": nodes, "edges": edges}


def render_graph_data(assessment: ImpactAssessment) -> dict[str, Any]:
    """Render entity graph as vis.js-compatible node/edge data."""
    nodes = []
    edges = []

    for entity in assessment.entity_graph.entities:
        node: dict[str, Any] = {
            "id": entity.id,
            "label": entity.name,
            "group": entity.entity_type,
            "title": f"{entity.entity_type} | {entity.country or 'Unknown'}",
        }
        # Color by type
        colors = {
            "company": "#4A90D9",
            "person": "#7B68EE",
            "government": "#DC143C",
            "vessel": "#2E8B57",
            "sanctions_list": "#F85149",
            "theme": "#F0883E",
            "sector": "#3FB950",
        }
        node["color"] = colors.get(entity.entity_type, "#808080")
        nodes.append(node)

    for rel in assessment.entity_graph.relationships:
        edge: dict[str, Any] = {
            "from": rel.source_id,
            "to": rel.target_id,
            "label": rel.relationship_type.replace("_", " "),
            "arrows": "to",
        }
        # Style by confidence
        if rel.confidence.value == "LOW":
            edge["dashes"] = True
        edges.append(edge)

    return {"nodes": nodes, "edges": edges}


def _confidence_badge(level: str) -> str:
    """Return a markdown badge for confidence level."""
    badges = {
        "HIGH": "**[HIGH]**",
        "MEDIUM": "*[MEDIUM]*",
        "LOW": "~[LOW]~",
    }
    return badges.get(level, f"[{level}]")
