"""Notification administration endpoints.

Currently exposes:
- POST /api/notifications/send-weekly-digest — token-protected; triggers
  the weekly email digest for every opt-in user. Designed to be called by
  the Render Cron Job (see render.yaml) on Monday mornings.
- POST /api/notifications/twilio/sms-webhook — Twilio inbound SMS callback
  for STOP / HELP / START keyword handling.

Future tasks will add:
- GET/PUT /api/me/preferences (Task 9, user-facing settings)
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from fastapi import APIRouter, BackgroundTasks, Depends, Header, HTTPException, Request
from fastapi.responses import Response
from pydantic import BaseModel, Field
from twilio.request_validator import RequestValidator

from src.auth import require_auth
from src.common.config import config
from src.db import get_db
from src.notifications.email_digest import build_week_data, send_weekly_digest
from src.notifications.synthesis import generate_opening_synthesis

if TYPE_CHECKING:
    from anthropic import Anthropic

log = logging.getLogger(__name__)

router = APIRouter(prefix="/api/notifications", tags=["notifications"])

# Separate router for /api/me/... endpoints. The notifications-admin router
# is prefixed at /api/notifications; /me/preferences is user-facing so it
# lives under /api/me/.
me_router = APIRouter(prefix="/api/me", tags=["me"])


def _require_cron_token(x_cron_token: str | None = Header(None)) -> None:
    """Reject requests that don't present the configured cron-auth token.

    The cron token is generated by Render at service-creation time
    (render.yaml has `generateValue: true`) and shared between the web
    service and the cron service. A missing or wrong token returns 403.
    """
    expected = config.notifications_cron_token
    if not expected:
        # If the server isn't configured with a token, refuse the request
        # rather than silently allowing all calls. This catches "I forgot
        # to set the env var" errors loudly.
        raise HTTPException(503, "NOTIFICATIONS_CRON_TOKEN not configured on server")
    if x_cron_token != expected:
        raise HTTPException(403, "invalid cron token")


def _get_anthropic_client() -> "Anthropic | None":
    """Return an Anthropic client if a key is configured, else None.

    Wrapped in a function rather than module-level so tests can monkey-patch
    and so the (heavyish) Anthropic import only runs when actually needed.
    """
    if not config.anthropic_api_key:
        return None
    from anthropic import Anthropic

    return Anthropic(api_key=config.anthropic_api_key)


def _eligible_users() -> list[dict]:
    """Return all users with email_enabled=1 AND an email address on file."""
    conn = get_db()
    try:
        rows = conn.execute(
            "SELECT username, email, phone_number, sms_enabled, email_enabled, timezone "
            "FROM users WHERE email_enabled = 1 AND email IS NOT NULL AND email != ''"
        ).fetchall()
    finally:
        conn.close()
    return [dict(r) for r in rows]


async def _send_one_digest(user: dict, anthropic_client: "Anthropic | None") -> None:
    """Build the week data for one user, attach the synthesis, and send."""
    try:
        week_data = await build_week_data(user["username"])
        week_data.opening_synthesis = generate_opening_synthesis(week_data, anthropic_client)
        send_weekly_digest(user, week_data)
    except Exception:
        # Per-user failures must not stop the rest of the run. send_weekly_digest
        # already logs to notification_log on its own failure path; this
        # catches build_week_data / synthesis errors.
        log.exception("digest send failed for username=%s", user.get("username"))


@router.post("/send-weekly-digest", dependencies=[Depends(_require_cron_token)])
async def send_weekly_digest_endpoint(background_tasks: BackgroundTasks):
    """Iterate opt-in users; enqueue a digest send for each.

    Returns immediately with the count of enqueued users. Actual sends run
    as BackgroundTasks so the cron HTTP call returns quickly and doesn't
    block on the SendGrid round-trip for every user serially.
    """
    users = _eligible_users()
    if not users:
        return {"enqueued": 0, "note": "no opt-in users with email"}

    anthropic_client = _get_anthropic_client()
    for user in users:
        background_tasks.add_task(_send_one_digest, user, anthropic_client)

    return {"enqueued": len(users)}


# --- Twilio inbound webhook (STOP / HELP / START) -------------------------
#
# Twilio configures this URL as the inbound-SMS callback for our Twilio
# number. When a user replies to an SMS we sent, Twilio POSTs form-encoded
# data here. Twilio also enforces STOP/HELP/START at the carrier level
# regardless — this handler keeps our DB state aligned with what the user
# actually did so future sends respect the opt-out / opt-in.
#
# Authenticity is enforced via X-Twilio-Signature (HMAC-SHA1 over the URL +
# sorted POST params, keyed by TWILIO_AUTH_TOKEN). Without this check anyone
# with the webhook URL could spoof STOP/HELP/START on behalf of other users.
# See _validate_twilio_signature below.

_HELP_TEXT_TEMPLATE = (
    "Emissary risk alerts. Reply STOP to unsubscribe, START to re-enable. Manage at {url}/settings"
)
_STOP_REPLY = "You have been unsubscribed from Emissary SMS alerts. Reply START to re-enable."
_START_REPLY = "Subscribed. You will receive HIGH-severity alerts for items on your watchlist."
_UNKNOWN_REPLY = "Number not recognized. Reply HELP for info."


def _twiml(message: str) -> Response:
    """Wrap `message` in TwiML XML and return as a 200 OK response."""
    # XML-escape the message contents. Twilio enforces a 1600-char hard limit
    # per response message; nothing we generate here comes close, but be
    # defensive about user-supplied content if this template ever grows.
    from xml.sax.saxutils import escape

    xml = f"<Response><Message>{escape(message)}</Message></Response>"
    return Response(content=xml, media_type="application/xml")


# --- Twilio signature validation helper -----------------------------------


async def _validate_twilio_signature(
    request: Request, prefetched_form: dict[str, str] | None = None
) -> None:
    """Reject the request if X-Twilio-Signature doesn't match.

    Bypassed when TWILIO_STUB_MODE is on so local dev works without real
    auth tokens. Returns 503 when the server has no TWILIO_AUTH_TOKEN
    configured (refuse rather than silently accept). Returns 403 when the
    signature is present but doesn't validate.

    Production note: Twilio signs the URL it called, which on Render is
    https:// even though the internal request is http:// behind the proxy.
    Reconstruct using APP_BASE_URL so the signature matches.

    `prefetched_form` lets the caller pass an already-parsed form dict so
    we don't re-read the request body (Starlette caches form() but we
    don't want to rely on that across FastAPI internals).
    """
    if config.twilio_stub_mode:
        return  # local-dev bypass

    if not config.twilio_auth_token:
        raise HTTPException(503, "TWILIO_AUTH_TOKEN not configured on server")

    signature = request.headers.get("X-Twilio-Signature", "")
    if not signature:
        raise HTTPException(403, "missing X-Twilio-Signature header")

    # Use APP_BASE_URL as the source of truth for what Twilio signed.
    # request.url.path keeps the path FastAPI saw; query string preserved too.
    base = config.app_base_url.rstrip("/")
    full_url = f"{base}{request.url.path}"
    if request.url.query:
        full_url = f"{full_url}?{request.url.query}"

    # Twilio signs ALL form params, not just From/Body — MessageSid, AccountSid,
    # ToCity, etc. all participate in the HMAC.
    if prefetched_form is None:
        form = await request.form()
        params = {k: v for k, v in form.items()}
    else:
        params = prefetched_form

    validator = RequestValidator(config.twilio_auth_token)
    if not validator.validate(full_url, params, signature):
        raise HTTPException(403, "invalid Twilio signature")


@router.post("/twilio/sms-webhook")
async def twilio_inbound_sms(request: Request) -> Response:
    """Handle inbound SMS from Twilio. Dispatches on the first keyword.

    We read the request body upfront so the signature validator can see
    ALL form params (Twilio signs the full set, not just From/Body) and
    so we don't double-parse the body. Empty Body falls through to the
    conversational-help branch rather than 422-ing — Twilio retries 422s
    and we'd rather degrade gracefully.
    """
    form = await request.form()
    params = {k: str(v) for k, v in form.items()}
    await _validate_twilio_signature(request, prefetched_form=params)

    from_ = params.get("From", "")
    body = params.get("Body", "")
    if not from_:
        raise HTTPException(422, "missing From field")

    keyword = body.strip().upper().split(maxsplit=1)[0] if body.strip() else ""

    conn = get_db()
    try:
        user_row = conn.execute(
            "SELECT username FROM users WHERE phone_number = ?", (from_,)
        ).fetchone()

        if user_row is None:
            return _twiml(_UNKNOWN_REPLY)

        if keyword == "STOP":
            conn.execute(
                "UPDATE users SET sms_enabled = 0, unsubscribed_at = CURRENT_TIMESTAMP "
                "WHERE phone_number = ?",
                (from_,),
            )
            conn.commit()
            log.info("STOP from %s; sms_enabled cleared", from_)
            return _twiml(_STOP_REPLY)

        if keyword in ("START", "UNSTOP"):
            conn.execute(
                "UPDATE users SET sms_enabled = 1, unsubscribed_at = NULL WHERE phone_number = ?",
                (from_,),
            )
            conn.commit()
            log.info("START/UNSTOP from %s; sms_enabled set", from_)
            return _twiml(_START_REPLY)

        if keyword == "HELP":
            return _twiml(_HELP_TEXT_TEMPLATE.format(url=config.app_base_url.rstrip("/")))

        # Any other body: treat as conversational; don't change state, just
        # echo a friendly help nudge. Logged at debug so it doesn't spam.
        log.debug("inbound from %s with body=%r — no keyword match", from_, body)
        return _twiml(_HELP_TEXT_TEMPLATE.format(url=config.app_base_url.rstrip("/")))
    finally:
        conn.close()


# --- /api/me/preferences (per-user GET/PUT) -------------------------------
#
# Bearer-authenticated. Returns / updates the calling user's row in the
# users table. PUT is upsert semantics (ON CONFLICT DO UPDATE) so the
# first-time save creates the row.

# E.164 phone format: '+' followed by 1-15 digits, leading digit non-zero.
_E164_PATTERN = r"^\+[1-9]\d{1,14}$"


class Preferences(BaseModel):
    email: str | None = Field(None, max_length=320)  # RFC 5321 max
    phone_number: str | None = Field(None, pattern=_E164_PATTERN)
    sms_enabled: bool = False
    email_enabled: bool = False
    timezone: str = Field("America/New_York", max_length=64)


@me_router.get("/preferences", response_model=Preferences)
def get_my_preferences(username: str = Depends(require_auth)) -> Preferences:
    conn = get_db()
    try:
        row = conn.execute(
            "SELECT email, phone_number, sms_enabled, email_enabled, timezone "
            "FROM users WHERE username = ?",
            (username,),
        ).fetchone()
    finally:
        conn.close()
    if row is None:
        # No row yet — return defaults. Caller is expected to PUT to create one.
        return Preferences()
    return Preferences(
        email=row["email"],
        phone_number=row["phone_number"],
        sms_enabled=bool(row["sms_enabled"]),
        email_enabled=bool(row["email_enabled"]),
        timezone=row["timezone"] or "America/New_York",
    )


@me_router.put("/preferences", response_model=Preferences)
def put_my_preferences(prefs: Preferences, username: str = Depends(require_auth)) -> Preferences:
    conn = get_db()
    try:
        conn.execute(
            "INSERT INTO users "
            "(username, email, phone_number, sms_enabled, email_enabled, timezone) "
            "VALUES (?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(username) DO UPDATE SET "
            "email = excluded.email, "
            "phone_number = excluded.phone_number, "
            "sms_enabled = excluded.sms_enabled, "
            "email_enabled = excluded.email_enabled, "
            "timezone = excluded.timezone",
            (
                username,
                prefs.email,
                prefs.phone_number,
                int(prefs.sms_enabled),
                int(prefs.email_enabled),
                prefs.timezone,
            ),
        )
        conn.commit()
    finally:
        conn.close()
    return prefs
