"""Notification administration endpoints.

Currently exposes:
- POST /api/notifications/send-weekly-digest — token-protected; triggers
  the weekly email digest for every opt-in user. Designed to be called by
  the Render Cron Job (see render.yaml) on Monday mornings.
- POST /api/notifications/twilio/sms-webhook — Twilio inbound SMS callback
  for STOP / HELP / START keyword handling.

Future tasks will add:
- GET/PUT /api/me/preferences (Task 9, user-facing settings)
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from fastapi import APIRouter, BackgroundTasks, Depends, Form, Header, HTTPException
from fastapi.responses import Response

from src.common.config import config
from src.db import get_db
from src.notifications.email_digest import build_week_data, send_weekly_digest
from src.notifications.synthesis import generate_opening_synthesis

if TYPE_CHECKING:
    from anthropic import Anthropic

log = logging.getLogger(__name__)

router = APIRouter(prefix="/api/notifications", tags=["notifications"])


def _require_cron_token(x_cron_token: str | None = Header(None)) -> None:
    """Reject requests that don't present the configured cron-auth token.

    The cron token is generated by Render at service-creation time
    (render.yaml has `generateValue: true`) and shared between the web
    service and the cron service. A missing or wrong token returns 403.
    """
    expected = config.notifications_cron_token
    if not expected:
        # If the server isn't configured with a token, refuse the request
        # rather than silently allowing all calls. This catches "I forgot
        # to set the env var" errors loudly.
        raise HTTPException(503, "NOTIFICATIONS_CRON_TOKEN not configured on server")
    if x_cron_token != expected:
        raise HTTPException(403, "invalid cron token")


def _get_anthropic_client() -> "Anthropic | None":
    """Return an Anthropic client if a key is configured, else None.

    Wrapped in a function rather than module-level so tests can monkey-patch
    and so the (heavyish) Anthropic import only runs when actually needed.
    """
    if not config.anthropic_api_key:
        return None
    from anthropic import Anthropic

    return Anthropic(api_key=config.anthropic_api_key)


def _eligible_users() -> list[dict]:
    """Return all users with email_enabled=1 AND an email address on file."""
    conn = get_db()
    try:
        rows = conn.execute(
            "SELECT username, email, phone_number, sms_enabled, email_enabled, timezone "
            "FROM users WHERE email_enabled = 1 AND email IS NOT NULL AND email != ''"
        ).fetchall()
    finally:
        conn.close()
    return [dict(r) for r in rows]


async def _send_one_digest(user: dict, anthropic_client: "Anthropic | None") -> None:
    """Build the week data for one user, attach the synthesis, and send."""
    try:
        week_data = await build_week_data(user["username"])
        week_data.opening_synthesis = generate_opening_synthesis(week_data, anthropic_client)
        send_weekly_digest(user, week_data)
    except Exception:
        # Per-user failures must not stop the rest of the run. send_weekly_digest
        # already logs to notification_log on its own failure path; this
        # catches build_week_data / synthesis errors.
        log.exception("digest send failed for username=%s", user.get("username"))


@router.post("/send-weekly-digest", dependencies=[Depends(_require_cron_token)])
async def send_weekly_digest_endpoint(background_tasks: BackgroundTasks):
    """Iterate opt-in users; enqueue a digest send for each.

    Returns immediately with the count of enqueued users. Actual sends run
    as BackgroundTasks so the cron HTTP call returns quickly and doesn't
    block on the SendGrid round-trip for every user serially.
    """
    users = _eligible_users()
    if not users:
        return {"enqueued": 0, "note": "no opt-in users with email"}

    anthropic_client = _get_anthropic_client()
    for user in users:
        background_tasks.add_task(_send_one_digest, user, anthropic_client)

    return {"enqueued": len(users)}


# --- Twilio inbound webhook (STOP / HELP / START) -------------------------
#
# Twilio configures this URL as the inbound-SMS callback for our Twilio
# number. When a user replies to an SMS we sent, Twilio POSTs form-encoded
# data here. Twilio also enforces STOP/HELP/START at the carrier level
# regardless — this handler keeps our DB state aligned with what the user
# actually did so future sends respect the opt-out / opt-in.
#
# NOTE: This endpoint is intentionally NOT protected by _require_cron_token
# because Twilio calls it from their IP range and cannot present our token.
# A future hardening pass should validate the X-Twilio-Signature header
# (requires TWILIO_AUTH_TOKEN), but that is out of scope for the demo.

_HELP_TEXT_TEMPLATE = (
    "Emissary risk alerts. Reply STOP to unsubscribe, START to re-enable. Manage at {url}/settings"
)
_STOP_REPLY = "You have been unsubscribed from Emissary SMS alerts. Reply START to re-enable."
_START_REPLY = "Subscribed. You will receive HIGH-severity alerts for items on your watchlist."
_UNKNOWN_REPLY = "Number not recognized. Reply HELP for info."


def _twiml(message: str) -> Response:
    """Wrap `message` in TwiML XML and return as a 200 OK response."""
    # XML-escape the message contents. Twilio enforces a 1600-char hard limit
    # per response message; nothing we generate here comes close, but be
    # defensive about user-supplied content if this template ever grows.
    from xml.sax.saxutils import escape

    xml = f"<Response><Message>{escape(message)}</Message></Response>"
    return Response(content=xml, media_type="application/xml")


@router.post("/twilio/sms-webhook")
def twilio_inbound_sms(From: str = Form(...), Body: str = Form("")) -> Response:
    """Handle inbound SMS from Twilio. Dispatches on the first keyword.

    `Body` defaults to "" so a malformed/empty inbound POST falls through
    to the conversational-help branch rather than 422-ing — Twilio retries
    422s, and we'd rather degrade gracefully.
    """
    keyword = Body.strip().upper().split(maxsplit=1)[0] if Body.strip() else ""

    conn = get_db()
    try:
        user_row = conn.execute(
            "SELECT username FROM users WHERE phone_number = ?", (From,)
        ).fetchone()

        if user_row is None:
            return _twiml(_UNKNOWN_REPLY)

        if keyword == "STOP":
            conn.execute(
                "UPDATE users SET sms_enabled = 0, unsubscribed_at = CURRENT_TIMESTAMP "
                "WHERE phone_number = ?",
                (From,),
            )
            conn.commit()
            log.info("STOP from %s; sms_enabled cleared", From)
            return _twiml(_STOP_REPLY)

        if keyword in ("START", "UNSTOP"):
            conn.execute(
                "UPDATE users SET sms_enabled = 1, unsubscribed_at = NULL WHERE phone_number = ?",
                (From,),
            )
            conn.commit()
            log.info("START/UNSTOP from %s; sms_enabled set", From)
            return _twiml(_START_REPLY)

        if keyword == "HELP":
            return _twiml(_HELP_TEXT_TEMPLATE.format(url=config.app_base_url.rstrip("/")))

        # Any other body: treat as conversational; don't change state, just
        # echo a friendly help nudge. Logged at debug so it doesn't spam.
        log.debug("inbound from %s with body=%r — no keyword match", From, Body)
        return _twiml(_HELP_TEXT_TEMPLATE.format(url=config.app_base_url.rstrip("/")))
    finally:
        conn.close()
