"""Notification administration endpoints.

Currently exposes:
- POST /api/notifications/send-weekly-digest — token-protected; triggers
  the weekly email digest for every opt-in user. Designed to be called by
  the Render Cron Job (see render.yaml) on Monday mornings.

Future tasks will add:
- POST /api/notifications/twilio/sms-webhook (Task 8, STOP/HELP/START)
- GET/PUT /api/me/preferences (Task 9, user-facing settings)
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from fastapi import APIRouter, BackgroundTasks, Depends, Header, HTTPException

from src.common.config import config
from src.db import get_db
from src.notifications.email_digest import build_week_data, send_weekly_digest
from src.notifications.synthesis import generate_opening_synthesis

if TYPE_CHECKING:
    from anthropic import Anthropic

log = logging.getLogger(__name__)

router = APIRouter(prefix="/api/notifications", tags=["notifications"])


def _require_cron_token(x_cron_token: str | None = Header(None)) -> None:
    """Reject requests that don't present the configured cron-auth token.

    The cron token is generated by Render at service-creation time
    (render.yaml has `generateValue: true`) and shared between the web
    service and the cron service. A missing or wrong token returns 403.
    """
    expected = config.notifications_cron_token
    if not expected:
        # If the server isn't configured with a token, refuse the request
        # rather than silently allowing all calls. This catches "I forgot
        # to set the env var" errors loudly.
        raise HTTPException(503, "NOTIFICATIONS_CRON_TOKEN not configured on server")
    if x_cron_token != expected:
        raise HTTPException(403, "invalid cron token")


def _get_anthropic_client() -> "Anthropic | None":
    """Return an Anthropic client if a key is configured, else None.

    Wrapped in a function rather than module-level so tests can monkey-patch
    and so the (heavyish) Anthropic import only runs when actually needed.
    """
    if not config.anthropic_api_key:
        return None
    from anthropic import Anthropic

    return Anthropic(api_key=config.anthropic_api_key)


def _eligible_users() -> list[dict]:
    """Return all users with email_enabled=1 AND an email address on file."""
    conn = get_db()
    try:
        rows = conn.execute(
            "SELECT username, email, phone_number, sms_enabled, email_enabled, timezone "
            "FROM users WHERE email_enabled = 1 AND email IS NOT NULL AND email != ''"
        ).fetchall()
    finally:
        conn.close()
    return [dict(r) for r in rows]


async def _send_one_digest(user: dict, anthropic_client: "Anthropic | None") -> None:
    """Build the week data for one user, attach the synthesis, and send."""
    try:
        week_data = await build_week_data(user["username"])
        week_data.opening_synthesis = generate_opening_synthesis(week_data, anthropic_client)
        send_weekly_digest(user, week_data)
    except Exception:
        # Per-user failures must not stop the rest of the run. send_weekly_digest
        # already logs to notification_log on its own failure path; this
        # catches build_week_data / synthesis errors.
        log.exception("digest send failed for username=%s", user.get("username"))


@router.post("/send-weekly-digest", dependencies=[Depends(_require_cron_token)])
async def send_weekly_digest_endpoint(background_tasks: BackgroundTasks):
    """Iterate opt-in users; enqueue a digest send for each.

    Returns immediately with the count of enqueued users. Actual sends run
    as BackgroundTasks so the cron HTTP call returns quickly and doesn't
    block on the SendGrid round-trip for every user serially.
    """
    users = _eligible_users()
    if not users:
        return {"enqueued": 0, "note": "no opt-in users with email"}

    anthropic_client = _get_anthropic_client()
    for user in users:
        background_tasks.add_task(_send_one_digest, user, anthropic_client)

    return {"enqueued": len(users)}
