// Export an orchestrator assessment as a takeaway artifact — markdown to the
// clipboard, or a paginated PDF of the rendered result.
import { jsPDF } from 'jspdf'
import html2canvas from 'html2canvas'
import type { ImpactAssessmentResult } from '../types'

export function assessmentToMarkdown(d: ImpactAssessmentResult): string {
  const lines: string[] = []
  lines.push('# Economic Warfare Assessment')
  if (d.query?.raw_query) lines.push(`**Query:** ${d.query.raw_query}`)
  if (d.scenario_type) lines.push(`**Scenario:** ${d.scenario_type.replace(/_/g, ' ')}`)
  lines.push('', '## Executive Assessment', d.executive_summary || '—')
  if (d.findings?.length) {
    lines.push('', '## Findings')
    d.findings.forEach((f) => lines.push(`- [${f.confidence}] ${f.category}: ${f.finding}`))
  }
  if (d.friendly_fire?.length) {
    lines.push('', '## Friendly-Fire Alerts')
    d.friendly_fire.forEach((f) => lines.push(`- ${f.entity}${f.details ? `: ${f.details}` : ''}`))
  }
  if (d.recommendations?.length) {
    lines.push('', '## Recommendations')
    d.recommendations.forEach((r, i) => lines.push(`${i + 1}. ${r}`))
  }
  if (d.sources?.length) {
    lines.push('', '## Sources')
    d.sources.forEach((s) => lines.push(`- ${s.name}${s.url ? ` (${s.url})` : ''}`))
  }
  lines.push('', `_Generated by Emissary · ${new Date().toLocaleString()}_`)
  return lines.join('\n')
}

export async function copyAssessment(d: ImpactAssessmentResult): Promise<void> {
  await navigator.clipboard.writeText(assessmentToMarkdown(d))
}

/** Render an element to a paginated A4 PDF and trigger a download. */
export async function downloadAssessmentPdf(el: HTMLElement, filename: string): Promise<void> {
  const canvas = await html2canvas(el, { backgroundColor: '#061033', scale: 2, useCORS: true })
  const img = canvas.toDataURL('image/png')
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' })
  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()
  const imgH = (canvas.height * pageW) / canvas.width
  let heightLeft = imgH
  let position = 0
  pdf.addImage(img, 'PNG', 0, position, pageW, imgH)
  heightLeft -= pageH
  while (heightLeft > 0) {
    position -= pageH
    pdf.addPage()
    pdf.addImage(img, 'PNG', 0, position, pageW, imgH)
    heightLeft -= pageH
  }
  pdf.save(filename)
}
